Repository knative-extensions/eventing-github, pull requests merged in 2020-11, with the labels that each got.

#58 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#59 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#60 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#61 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#62 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#63 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/pkg/kncloudevents/http_client.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#66 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#67 Fix a few more occurrences of divisive language
  config/core/placeholder.go
  config/mt-github/placeholder.go
  config/placeholder.go
Labels: approved, cla: yes, lgtm, size/XS

#68 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_matchers.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_info_store.go
  vendor/knative.dev/eventing/test/lib/recordevents/event_log.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/receiver.go
  vendor/knative.dev/eventing/test/lib/recordevents/receiver/reply.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/constructor.go
  vendor/knative.dev/eventing/test/lib/recordevents/recorder_vent/recorder.go
  vendor/knative.dev/eventing/test/lib/recordevents/resources.go
  vendor/knative.dev/eventing/test/lib/recordevents/sender/sender.go
  vendor/knative.dev/eventing/test/lib/sender/resources.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/reconciler/testing/tracker.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#70 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#71 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/env.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#72 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#73 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/logconfig/config.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#74 Get webhook name from common pkg
  cmd/webhook/main.go
  vendor/knative.dev/eventing/pkg/logconfig/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#75 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/client/client.go
  vendor/knative.dev/eventing/pkg/client/injection/client/client.go
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/serving/pkg/client/injection/client/client.go
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#76 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/pkg/webhook/psbinding/index.go
  vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
