Repository knative-extensions/eventing-github, pull requests merged in 2021-08, with the labels that each got.

#183 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/XS

#186 bump go to 1.16
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/S

#187 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/M, approved, lgtm

#188 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, approved, lgtm, size/XS

#189 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#192 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, approved, lgtm, size/XS

#194 Use `controller.Impl` tracker and cleanups
  pkg/reconciler/binding/controller.go
  pkg/reconciler/source/controller.go
Labels: cla: yes, kind/cleanup, approved, lgtm, size/S

#193 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, size/M, approved, lgtm

#196 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, approved, lgtm, size/S

#197 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: cla: yes, size/M, approved, lgtm
