Repository knative-extensions/eventing-github, pull requests merged in 2022-10, with the labels that each got.

#334 Update deps and bump cloudevents/sdk-go/sql to 52b12276cc4a
  go.mod
  go.sum
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_config_set.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserialization_options.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserializer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/error_strategy.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/lexer_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/ll1_analyzer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/recognizer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/semantic_context.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/tree.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils_set.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/observability_service.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/observable.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/reporter.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/client/trace_attributes.go
  vendor/github.com/cloudevents/sdk-go/observability/opencensus/v2/http/http.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/README.md
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParser.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParserLexer.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_base_visitor.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_lexer.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_parser.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_visitor.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/utility.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#335 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#336 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#337 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#339 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#340 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#341 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#342 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS
