Repository knative-extensions/eventing-github, pull requests merged in 2022-03, with the labels that each got.

#245 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_386.go
  vendor/golang.org/x/sys/unix/syscall_linux_alarm.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_mipsx.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/syscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_386.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm

#244 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#246 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#247 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#249 Update sponsoring WG
  README.md
Labels: approved, lgtm, size/XS

#250 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#253 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#252 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#256 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#258 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, size/XL, lgtm

#257 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/eventing/test/lib/client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#259 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS
