Repository knative-extensions/eventing-github, pull requests merged in 2022-08, with the labels that each got.

#305 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm

#306 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#308 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#310 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#311 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#312 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#313 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#309 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/setup.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#314 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#315 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#316 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#318 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#317 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/config.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_configmap.go
  vendor/knative.dev/eventing/pkg/adapter/v2/configurator_environment.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main.go
  vendor/knative.dev/eventing/pkg/adapter/v2/main_message.go
  vendor/knative.dev/eventing/test/test_images/event-sender/main.go
  vendor/knative.dev/eventing/test/test_images/recordevents/main.go
  vendor/knative.dev/eventing/test/test_images/utils.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#319 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#320 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S

#321 fix verify codegen
  go.mod
  hack/verify-codegen.sh
  third_party/go.mod
Labels: approved, lgtm, size/XS

#322 [release-1.7] fix verify codegen
  go.mod
  hack/verify-codegen.sh
  third_party/go.mod
Labels: approved, lgtm, size/XS

#323 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/modules.txt
Labels: approved, lgtm, size/S
