Repository knative-extensions/eventing-github, pull requests merged in 2023-01, with the labels that each got.

#347 Add TEST README.md fixes #344
  test/README.md
Labels: ok-to-test, size/M, approved, lgtm

#357 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#358 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#359 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#355 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/sql/v2/parser/expression_visitor.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/utils/casting.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/abuse_protection.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/test/lib/logexporter.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/logstream/v2/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_defaults.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm
