Repository knative-extensions/eventing-github, pull requests merged in 2023-10, with the labels that each got.

#407 Add `.spec.secure` field to CRD
  config/core/300-githubsource.yaml
Labels: approved, lgtm, size/XS

#413 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/fake/fake_broker.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1/fake/fake_trigger.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/flows/v1/fake/fake_parallel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/flows/v1/fake/fake_sequence.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/fake/fake_channel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/fake/fake_inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1/fake/fake_subscription.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta2/fake/fake_pingsource.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#415 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#414 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#416 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#419 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#420 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#423 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#424 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm

#425 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_lifecycle.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#427 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_lifecycle.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#428 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#430 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#429 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#431 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#432 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/S
