Repository knative-extensions/eventing-github, pull requests merged in 2023-11, with the labels that each got.

#434 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#435 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#436 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#437 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#439 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#440 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/modules.txt
Labels: size/M, approved, lgtm

#441 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#443 Make SECURITY.md consistent
  SECURITY.md
Labels: approved, lgtm, size/XS

#442 Add timeouts on receive adapter
  pkg/adapter/adapter.go
  pkg/mtadapter/adapter.go
Labels: approved, lgtm, size/S

#444 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#445 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS, skip-review

#449 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
