Repository knative-extensions/eventing-github, pull requests merged in 2024-09, with the labels that each got.

#549 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.defaults.go
  vendor/knative.dev/eventing/pkg/apis/sinks/v1alpha1/zz_generated.defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/zz_generated.defaults.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/eventing/interface.go
  vendor/knative.dev/eventing/pkg/client/informers/externalversions/sources/interface.go
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#550 Migrate to kube_gen
  hack/update-codegen.sh
  pkg/apis/bindings/v1alpha1/zz_generated.defaults.go
  pkg/apis/sources/v1alpha1/zz_generated.defaults.go
  pkg/client/injection/informers/sources/factory/fake/fake.go
  pkg/client/injection/informers/sources/factory/sourcesfactory.go
  pkg/client/injection/reconciler/sources/v1alpha1/githubsource/stub/controller.go
  pkg/client/injection/reconciler/sources/v1alpha1/githubsource/stub/reconciler.go
Labels: approved, lgtm, size/S

#552 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#551 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/M, approved, lgtm

#557 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/controller.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/reconcile_config.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, size/L
